"""SYNTHETIC IndiGo extraction payloads for the automated-collection tests.

**Nothing here is market data.** Flight numbers are in the 6E 9xxx range on
purpose so no fixture row can be mistaken for a real DEL-BOM flight, and every
price is generated from a formula below. What *is* taken from reality is the
display format -- the strings goindigo.in rendered in the 2026-09-12 manual
screenshots (``6E 6218``, ``02h 15m``, ``Non-stop``, ``Saver fare``,
``15 kg Check-in bag allowance``, ``Change and cancellation charges``).

Each standard day deliberately contains the traps the rules must survive,
listed in **cheapest-first page order** because that is IndiGo's default sort:

=========  ==========  ============================================  ==========
dep        flight      trap                                          expected
=========  ==========  ============================================  ==========
05:40      6E 9001     before 06:00                                  ineligible
06:05      6E 9101     earliest in band 2 but the DEAREST of three   SELECTED
07:20      6E 9102     cheaper, later                                not taken
08:40      6E 9103     cheapest in band 2                            not taken
09:10      6E 9201     one stop                                      ineligible
09:45      6E 9202     codeshare, operated by another carrier        ineligible
10:30      6E 9203     earliest eligible in band 3                   SELECTED
12:15      6E 9301     departs from HDO, an alternate Delhi airport  ineligible
13:00      6E 9302     earliest eligible in band 4                   SELECTED
15:05      6E 9401     earliest in band 5                            SELECTED
18:30      6E 9501     earliest in band 6                            SELECTED
19:10      6E 9502     later in band 6                               not taken
21:15      6E 9601     after 20:59                                   ineligible
=========  ==========  ============================================  ==========

Per-date variations in :func:`build_fixture`:

* T+1  -- band 6's selected flight has its Saver sold out -> unpriced, not replaced
* T+15 -- no flight in band 4 at all                     -> empty band, not borrowed
* T+30 -- band 5's selected flight offers no Saver tile  -> excluded, Lite not substituted

The committed ``tests/fixtures/indigo/extract_2026-09-15.json`` is generated by
:func:`build_fixture` and a test asserts the two are identical, so the JSON
cannot drift from this documented construction.
"""

from __future__ import annotations

from datetime import date, timedelta

RUPEE = "₹"
COLLECTION_DATE = date(2026, 9, 15)
FROZEN_APW = (1, 3, 7, 15, 30, 45, 60)
BASE_PRICE = {1: 7800, 3: 7100, 7: 6500, 15: 6100, 30: 5600, 45: 5400, 60: 5300}
STANDARD_POLICY = "Change and cancellation charges: Standard"


def money(amount: int) -> str:
    return f"{RUPEE}{amount:,}"


def ordinal_label(d: date) -> str:
    suffix = "th" if 11 <= d.day % 100 <= 13 else {1: "st", 2: "nd", 3: "rd"}.get(d.day % 10, "th")
    return f"{d.day}{suffix} {d:%b}"


def tile(
    family: str,
    price: int,
    *,
    bag_kg: int,
    available: bool = True,
    concession: bool = False,
    policy: tuple[str, ...] = (STANDARD_POLICY,),
    breakdown: bool = True,
) -> dict[str, object]:
    base = round(price * 0.78)
    entitlements = ["7 kg Cabin bag allowance"]
    entitlements.append(
        f"{bag_kg} kg Check-in bag allowance" if bag_kg else "No check-in bag included"
    )
    return {
        "family": family,
        "price": money(price),
        "available": available,
        "concession": concession,
        "entitlements": entitlements,
        "policy": list(policy),
        "breakdown": (
            {
                "Base Airfare": money(base),
                "Total Tax": money(price - base),
                "TOTAL FARE": money(price),
            }
            if breakdown
            else {}
        ),
    }


def standard_tiles(saver_price: int) -> list[dict[str, object]]:
    return [
        tile("Lite fare", saver_price - 225, bag_kg=0),
        tile("Saver fare", saver_price, bag_kg=15),
        tile(
            "Flexi fare",
            saver_price + 1500,
            bag_kg=15,
            policy=("Free date change", "Cancellation fee applies"),
        ),
    ]


def card(
    label: str,
    departure: str,
    arrival: str,
    duration: str,
    fares: list[dict[str, object]],
    *,
    origin: str = "DEL, T1",
    destination: str = "BOM, T2",
    stops: str = "Non-stop",
    operated_by: str = "",
    sold_out: bool = False,
    departure_day_offset: int = 0,
) -> dict[str, object]:
    return {
        "flight_label": label,
        "departure": departure,
        "arrival": arrival,
        "departure_day_offset": departure_day_offset,
        "origin_label": origin,
        "destination_label": destination,
        "duration": duration,
        "stops": stops,
        "operated_by": operated_by,
        "sold_out": sold_out,
        "fares": fares,
    }


def echo(
    travel_date: date,
    *,
    origin: str = "DEL",
    destination: str = "BOM",
    passengers: str = "1 Passenger",
    currency: str = "INR",
    trip: str = "One Way",
) -> dict[str, str]:
    return {
        "origin": origin,
        "destination": destination,
        "date_label": ordinal_label(travel_date),
        "passengers_label": passengers,
        "currency_label": currency,
        "trip_label": trip,
    }


def results_page(
    travel_date: date, flights: list[dict[str, object]], **echo_kw: str
) -> dict[str, object]:
    return {
        "schema": "indigo-extract/1",
        "page": {"kind": "results", "http_status": 200, "message": ""},
        "search_echo": echo(travel_date, **echo_kw),
        "flights": flights,
    }


def non_results_page(kind: str, message: str, http_status: int = 200) -> dict[str, object]:
    return {
        "schema": "indigo-extract/1",
        "page": {"kind": kind, "http_status": http_status, "message": message},
        "search_echo": {},
        "flights": [],
    }


def _saver_price(card_: dict[str, object]) -> int:
    for t in card_["fares"]:  # type: ignore[attr-defined]
        if t["family"] == "Saver fare":
            return int(str(t["price"]).replace(RUPEE, "").replace(",", ""))
    return 10**9


def standard_flights(base: int) -> list[dict[str, object]]:
    """One day's flight universe, returned in cheapest-first page order."""
    flights = [
        card("6E 9001", "05:40", "07:55", "02h 15m", standard_tiles(base - 600)),
        card("6E 9101", "06:05", "08:20", "02h 15m", standard_tiles(base + 400)),
        card("6E 9102", "07:20", "09:35", "02h 15m", standard_tiles(base + 100)),
        card("6E 9103", "08:40", "10:55", "02h 15m", standard_tiles(base - 200)),
        card("6E 9201", "09:10", "13:40", "04h 30m", standard_tiles(base - 900), stops="1 Stop"),
        card(
            "6E 9202",
            "09:45",
            "12:00",
            "02h 15m",
            standard_tiles(base - 300),
            operated_by="Operated by Partner Air",
        ),
        card("6E 9203", "10:30", "12:45", "02h 15m", standard_tiles(base + 50)),
        card("6E 9301", "12:15", "14:35", "02h 20m", standard_tiles(base - 400), origin="HDO, T1"),
        card("6E 9302", "13:00", "15:15", "02h 15m", standard_tiles(base + 250)),
        card("6E 9401", "15:05", "17:25", "02h 20m", standard_tiles(base + 150)),
        card("6E 9501", "18:30", "20:45", "02h 15m", standard_tiles(base + 700)),
        card("6E 9502", "19:10", "21:25", "02h 15m", standard_tiles(base + 300)),
        card("6E 9601", "21:15", "23:30", "02h 15m", standard_tiles(base - 800)),
    ]
    return sorted(flights, key=lambda c: (_saver_price(c), str(c["flight_label"])))


def day_payload(lead_time: int, collection_date: date = COLLECTION_DATE) -> dict[str, object]:
    travel = collection_date + timedelta(days=lead_time)
    flights = standard_flights(BASE_PRICE[lead_time])
    if lead_time == 1:
        for c in flights:
            if c["flight_label"] == "6E 9501":
                for t in c["fares"]:  # type: ignore[attr-defined]
                    if t["family"] == "Saver fare":
                        t["available"] = False
    elif lead_time == 15:
        flights = [c for c in flights if c["flight_label"] not in ("6E 9301", "6E 9302")]
    elif lead_time == 30:
        for c in flights:
            if c["flight_label"] == "6E 9401":
                c["fares"] = [t for t in c["fares"] if t["family"] != "Saver fare"]  # type: ignore[attr-defined]
    return results_page(travel, flights)


def build_fixture(collection_date: date = COLLECTION_DATE) -> dict[str, object]:
    return {
        "data_class": "SYNTHETIC_FIXTURE",
        "description": (
            "SYNTHETIC IndiGo extraction payloads. Not market data: flight numbers "
            "6E 9xxx are invented and prices are formula-generated. Display formats "
            "follow the 2026-09-12 manual screenshots. Generated by "
            "tests/fixtures/indigo_synthetic.py::build_fixture."
        ),
        "collection_date": collection_date.isoformat(),
        "pages": {
            (collection_date + timedelta(days=n)).isoformat(): day_payload(n, collection_date)
            for n in FROZEN_APW
        },
    }
